FROM --platform=linux/amd64 node:18.15-alpine

WORKDIR /app
COPY package.json .
COPY vite.config.js .
COPY svelte.config.js .

RUN npm install

COPY src ./src
COPY static ./static

RUN npm run build

EXPOSE 3000
# ENV HOST=0.0.0.0
CMD ["node", "build"]
