  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@$$w0rd
      MYSQL_DATABASE: dad_gpt3
      MYSQL_USER: brett
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  backend:
    image: balbano/dadgpt-backend:0.2-linux
    links:
      - database
    ports:
      - 443:3000
  frontend:
    image: balbano/dadgpt-frontend:0.2-linux
    links:
      - backend
    depends_on:
      - backend
      - database
    environment:
      PUBLIC_HOSTNAME: $PUBLIC_HOSTNAME
    ports:
      - 80:3000
